language: python
python:
- "3.7"
cache: pip
install:
- pip install -r requirements.txt
script:
- python app.py
deploy:
provider: gae
keyfile: $248504  # "YOUR SERVICE ACCOUNT JSON FILE"
project: $Homework3  #"YOUR PROJECT ID
